In [1]:
import time
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from utilities import *

## 7 Incorporating Conditional Information

### 7.1 Approach I

#### Basic problem:

\begin{equation}
\min_{M_1\geq0}{\mathbb E}\left[M_1g(X_1)\right]
\end{equation}
*subject to constraints:*
\begin{align*}
&{\mathbb E}\left[M_1 \log M_1\right] \leq \kappa, \\
&{\mathbb E}\left[B^j M_1 f(X_1)\right] = 0, \\
&{\mathbb E}\left[M_1\right] = 1.
\end{align*}

#### Dual problem:

For computational purposes, we solve the dual problem after minimizing over $M_1$.  

\begin{equation*}
\sup_{\xi>0}\max_{\hat{\lambda}_j}    - \xi \log {\mathbb E} \left[ \exp\left( - {\frac 1 {\xi}} \left[ g(X_1) + \sum_{j=1}^{3}\hat{\lambda}_j \cdot f(X_1)B^j \right] \right)\right]  -  \xi \kappa  
\end{equation*}

$\hat{\lambda}$ and $\xi$ are multipliers on the moment condition and relative entropy constraints. 

### 7.2 Approach II

#### Basic problem:

\begin{equation}
\min_{M_1\geq0}{\mathbb E}\left[M_1g(X_1)\right]
\end{equation}
*subject to constraints:*
\begin{align*}
&{\mathbb E}\left[M_1 \log M_1\right] \leq \kappa, \\
&{\mathbb E}\left[B^j M_1 {f(X_1)}\right] = 0, \\
&{\mathbb E}\left[B^j M_1-B^j\right] = 0.
\end{align*}

#### Dual problem:

??

### 7.3 Approach III

#### Basic problem:

\begin{equation}
\min_{M_1\geq0}{\mathbb E}\left[M_1g(X_1)\mid\mathfrak{F}_0\right]
\end{equation}
*subject to constraints:*
\begin{align*}
&{\mathbb E}\left[M_1 \log M_1\mid\mathfrak{F}_0\right] \leq \kappa, \\
&{\mathbb E}\left[M_1  f(X_1)\mid\mathfrak{F}_0\right] = 0, \\
&{\mathbb E}\left[M_1\mid\mathfrak{F}_0\right] = 1.
\end{align*}

#### Dual problem:
For computational purposes, we solve the dual problem after minimizing over $M_1$.  

\begin{equation*}
\sup_{\xi>0}\max_{\hat{\lambda}}    - \xi \log {\mathbb E} \left[ \exp\left( - {\frac 1 {\xi}} \left[ g(X_1) + \hat{\lambda} \cdot f(X_1) \right] \right)\mid\mathfrak{F}_0\right]  -  \xi \kappa  
\end{equation*}

$\hat{\lambda}$ and $\xi$ are multipliers on the moment condition and relative entropy constraints. 

## 8 Intertemporal Divergence Constraints

### Proposition 8.6
Problem 8.4 can be solved by finding the solution to:

\begin{equation}
\epsilon = \min_\hat{\lambda}\mathbb E \left(\exp \left[-\frac{1}{\xi}g(X_1)+\hat{\lambda}\cdot f(X_1)\right]\left( \frac{e_1}{e_0}\right) \mid \mathfrak{F}_0\right)
\end{equation}

*where*
\begin{align*}
\mu &= -\xi \log \epsilon,\\
v_0 &= -\xi \log e_0.
\end{align*}

Denote $e^*$, $\hat{\lambda}^*$ as the solution to the above optimization problem. The implied solution for the probablity distortion is:

\begin{equation}
M_1^* = \frac{\exp \left[-\frac{1}{\xi}g(X_1)+\hat{\lambda}^*(Z_0)\cdot f(X_1)\right]e_1^*}{\epsilon^*e_0^*}
\end{equation}

In [5]:
# Set ξ
ξ = 1.

# Set model paramters
tol = 1e-7
max_iter = 1000

solver = intertemporal_div_constraint(tol,max_iter)

time_start = time.time() 
result = solver.iterate(ξ)

# Print iteration information
print("--- Iteration Ends ---")
print("ξ = %s" % ξ)
print("Time spent: %s seconds ---" % (round(time.time()-time_start,4)))
print("Numer of iterations: %s ---" % result['count'])

# Print converged parameter results
print("\n")
print("--- Converged parameter vlues ---")
print("ϵ: %s" % result['ϵ'])
print("e: %s" % result['e'])
print("λ: %s" % result['λ'])
print("μ: %s" % result['μ'])

# Print E[M|state k]
print("\n")
print("--- Check 1 ---")
print("E[M|state 1] = %s " % result['E_M_cond'][0])
print("E[M|state 2] = %s " % result['E_M_cond'][0])
print("E[M|state 3] = %s " % result['E_M_cond'][0])

# Print two ways of calculating moment bound
print("\n")
print("--- Check 2 ---")
print("E[Mg(X)] = %s (directly using M)" % result['moment_bound'])
print("E[Mg(X)] = %s (indirectly using μ and RE)" % result['moment_bound_check'])
print("Difference: %s" % (result['moment_bound']-result['moment_bound_check']))

# Print transition probability matrix
print("\n")
print("--- Transition Probability Matrix ---")
print(result['P'])

# Print stationary distribution
print("\n")
print("--- Stationary Distribution ---")
print(result['π'])

# Print conditional relative entropy
print("\n")
print("--- Conditional Relative Entropy ---")
print("E[MlogM|state 1] = %s " % result['RE_cond'][0])
print("E[MlogM|state 2] = %s " % result['RE_cond'][1])
print("E[MlogM|state 3] = %s " % result['RE_cond'][2])

# Print unconditional relative entropy
print("\n")
print("--- Unconditional Relative Entropy ---")
print("E[MlogM] = %s " % result['RE'])

# Print conditional moment bound
print("\n")
print("--- Conditional Moment Bound ---")
print("E[Mg(X)|state 1] = %s " % result['moment_bound_cond'][0])
print("E[Mg(X)|state 2] = %s " % result['moment_bound_cond'][1])
print("E[Mg(X)|state 3] = %s " % result['moment_bound_cond'][2])

# Print unconditional moment bound
print("\n")
print("--- Unconditional Moment Bound ---")
print("E[Mg(X)] = %s " % result['moment_bound'])

--- Iteration Ends ---
ξ = 1.0
Time spent: 0.3192 seconds ---
Numer of iterations: 148 ---


--- Converged parameter vlues ---
ϵ: 0.9662646649208998
e: [1.         0.44191842 0.19224352]
λ: [ 1.20452948  0.79543571 -0.31097385 -0.76108306  1.42677063  0.57334818
  0.66141466 -5.97029601  2.68481185 -0.68484044 -3.48387392 -7.80333534]
μ: 0.034317502045974856


--- Check 1 ---
E[M|state 1] = 0.9999999995442487 
E[M|state 2] = 0.9999999995442487 
E[M|state 3] = 0.9999999995442487 


--- Check 2 ---
E[Mg(X)] = 0.00575736621110245 (directly using M)
E[Mg(X)] = 0.005756523067879365 (indirectly using μ and RE)
Difference: 8.431432230848052e-07


--- Transition Probability Matrix ---
[[0.97954806 0.02045194 0.        ]
 [0.0840223  0.88101511 0.03496256]
 [0.         0.17514739 0.82485237]]


--- Stationary Distribution ---
[0.77399375 0.1883985  0.03760776]


--- Conditional Relative Entropy ---
E[MlogM|state 1] = 0.0124037070667327 
E[MlogM|state 2] = 0.06706643710381138 
E[MlogM|state 3] =

In [14]:
# Solve the minimization problems over a grid of ξ
tol = 1e-7
max_iter = 1000

solver = intertemporal_div_constraint(tol,max_iter)

# Grid for ξ
ξ_grid = np.arange(.01,1.,.01)
μs = np.zeros_like(ξ_grid)
REs = np.zeros_like(ξ_grid)
bounds = np.zeros_like(ξ_grid)
ϵs = np.zeros_like(ξ_grid)

time_start = time.time() 
for i in range(len(ξ_grid)):
    ξ = ξ_grid[i]
    result = solver.iterate(ξ)
    μs[i] = result['μ']
    REs[i] = result['RE']
    bounds[i] = result['moment_bound']
    ϵs[i] = result['ϵ']

print("Time spent: %s seconds ---" % (round(time.time()-time_start,4)))

Time spent: 30.9794 seconds ---


In [16]:
# Plots for μ and RE
fig = make_subplots(rows=1, cols=2)
fig.add_trace(
    go.Scatter(x=ξ_grid, y=bounds, name='E[Mg(X)]'),
    row=1, col=1
)
fig.add_trace(
    go.Scatter(x=ξ_grid, y=REs, name='RE'),
    row=1, col=2
)
fig.update_layout(height=400, width=1000,title_text='Plots over ξ')
fig.update_xaxes(rangemode="tozero",title_text='ξ')
fig.update_yaxes(rangemode="tozero")
fig.show()